# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nxirda/Desktop/PPN_Projet_MEM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nxirda/Desktop/PPN_Projet_MEM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nxirda/Desktop/PPN_Projet_MEM/CMakeFiles /home/nxirda/Desktop/PPN_Projet_MEM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nxirda/Desktop/PPN_Projet_MEM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named Tests

# Build rule for target.
Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tests
.PHONY : Tests

# fast build rule for target.
Tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/build
.PHONY : Tests/fast

#=============================================================================
# Target rules for targets named Benchmarks

# Build rule for target.
Benchmarks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Benchmarks
.PHONY : Benchmarks

# fast build rule for target.
Benchmarks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Benchmarks.dir/build.make CMakeFiles/Benchmarks.dir/build
.PHONY : Benchmarks/fast

#=============================================================================
# Target rules for targets named Source_Lib

# Build rule for target.
Source_Lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Source_Lib
.PHONY : Source_Lib

# fast build rule for target.
Source_Lib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Source_Lib.dir/build.make src/CMakeFiles/Source_Lib.dir/build
.PHONY : Source_Lib/fast

#=============================================================================
# Target rules for targets named Test_Lib

# Build rule for target.
Test_Lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Test_Lib
.PHONY : Test_Lib

# fast build rule for target.
Test_Lib/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/Test_Lib.dir/build.make test/CMakeFiles/Test_Lib.dir/build
.PHONY : Test_Lib/fast

#=============================================================================
# Target rules for targets named Benchmark_Lib

# Build rule for target.
Benchmark_Lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Benchmark_Lib
.PHONY : Benchmark_Lib

# fast build rule for target.
Benchmark_Lib/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/Benchmark_Lib.dir/build.make benchmark/CMakeFiles/Benchmark_Lib.dir/build
.PHONY : Benchmark_Lib/fast

benchmark/mainBenchmark.o: benchmark/mainBenchmark.cpp.o
.PHONY : benchmark/mainBenchmark.o

# target to build an object file
benchmark/mainBenchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Benchmarks.dir/build.make CMakeFiles/Benchmarks.dir/benchmark/mainBenchmark.cpp.o
.PHONY : benchmark/mainBenchmark.cpp.o

benchmark/mainBenchmark.i: benchmark/mainBenchmark.cpp.i
.PHONY : benchmark/mainBenchmark.i

# target to preprocess a source file
benchmark/mainBenchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Benchmarks.dir/build.make CMakeFiles/Benchmarks.dir/benchmark/mainBenchmark.cpp.i
.PHONY : benchmark/mainBenchmark.cpp.i

benchmark/mainBenchmark.s: benchmark/mainBenchmark.cpp.s
.PHONY : benchmark/mainBenchmark.s

# target to generate assembly for a file
benchmark/mainBenchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Benchmarks.dir/build.make CMakeFiles/Benchmarks.dir/benchmark/mainBenchmark.cpp.s
.PHONY : benchmark/mainBenchmark.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

test/DataSet_Test.o: test/DataSet_Test.cpp.o
.PHONY : test/DataSet_Test.o

# target to build an object file
test/DataSet_Test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/DataSet_Test.cpp.o
.PHONY : test/DataSet_Test.cpp.o

test/DataSet_Test.i: test/DataSet_Test.cpp.i
.PHONY : test/DataSet_Test.i

# target to preprocess a source file
test/DataSet_Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/DataSet_Test.cpp.i
.PHONY : test/DataSet_Test.cpp.i

test/DataSet_Test.s: test/DataSet_Test.cpp.s
.PHONY : test/DataSet_Test.s

# target to generate assembly for a file
test/DataSet_Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/DataSet_Test.cpp.s
.PHONY : test/DataSet_Test.cpp.s

test/DecisionTree_Test.o: test/DecisionTree_Test.cpp.o
.PHONY : test/DecisionTree_Test.o

# target to build an object file
test/DecisionTree_Test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/DecisionTree_Test.cpp.o
.PHONY : test/DecisionTree_Test.cpp.o

test/DecisionTree_Test.i: test/DecisionTree_Test.cpp.i
.PHONY : test/DecisionTree_Test.i

# target to preprocess a source file
test/DecisionTree_Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/DecisionTree_Test.cpp.i
.PHONY : test/DecisionTree_Test.cpp.i

test/DecisionTree_Test.s: test/DecisionTree_Test.cpp.s
.PHONY : test/DecisionTree_Test.s

# target to generate assembly for a file
test/DecisionTree_Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/DecisionTree_Test.cpp.s
.PHONY : test/DecisionTree_Test.cpp.s

test/TreeNode_Test.o: test/TreeNode_Test.cpp.o
.PHONY : test/TreeNode_Test.o

# target to build an object file
test/TreeNode_Test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/TreeNode_Test.cpp.o
.PHONY : test/TreeNode_Test.cpp.o

test/TreeNode_Test.i: test/TreeNode_Test.cpp.i
.PHONY : test/TreeNode_Test.i

# target to preprocess a source file
test/TreeNode_Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/TreeNode_Test.cpp.i
.PHONY : test/TreeNode_Test.cpp.i

test/TreeNode_Test.s: test/TreeNode_Test.cpp.s
.PHONY : test/TreeNode_Test.s

# target to generate assembly for a file
test/TreeNode_Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/test/TreeNode_Test.cpp.s
.PHONY : test/TreeNode_Test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Benchmark_Lib"
	@echo "... Benchmarks"
	@echo "... Source_Lib"
	@echo "... Test_Lib"
	@echo "... Tests"
	@echo "... main"
	@echo "... benchmark/mainBenchmark.o"
	@echo "... benchmark/mainBenchmark.i"
	@echo "... benchmark/mainBenchmark.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test/DataSet_Test.o"
	@echo "... test/DataSet_Test.i"
	@echo "... test/DataSet_Test.s"
	@echo "... test/DecisionTree_Test.o"
	@echo "... test/DecisionTree_Test.i"
	@echo "... test/DecisionTree_Test.s"
	@echo "... test/TreeNode_Test.o"
	@echo "... test/TreeNode_Test.i"
	@echo "... test/TreeNode_Test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

